[env:stackchan]
platform = espressif32
board = m5stack-cores3
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep
build_unflags =
  -std=gnu++11
build_flags =
  -std=gnu++17
lib_deps =
  https://github.com/stack-chan/stackchan-arduino.git
