use_default_settings:
  engines:
    keep_only:
      - duckduckgo
      - wikipedia
      - brave

server:
  bind_address: "0.0.0.0"
  port: 8080
  limiter: false
  image_proxy: false

search:
  safe_search: 1
  autocomplete: ""
  default_lang: "en"
  formats:
    - json

ui:
  static_use_hash: true

outgoing:
  request_timeout: 4.0
  max_request_timeout: 8.0
